Bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get "home/about" => "home#about"
  resources :books, except: [:new]
  resources :users, except: [:new, :destroy, :create]
end

Bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers2/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  # title：空でないように設定してください。
  # body：空でない、かつ最大200文字までに設定してください。
  validates :title, :body, presence: true
  validates :body, length: { maximum: 200 }
end

Bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image

  # name：一意性を持たせ、かつ2～20文字の範囲で設定してください。
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }

  #  introduction：最大50文字までに設定してください。

  validates :introduction, length: { maximum: 50 }
end

Bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

Bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @user = current_user
      render action: :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user_sidebar = @book.user
    @book_sidebar = Book.new
  end

  def edit
    @book = Book.find(params[:id])

    unless @book.user == current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      @user = current_user
      render action: :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

Bookers2/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

Bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user_sidebar = User.find(current_user.id)
    @book_sidebar = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.reverse_order
    @user_sidebar = User.find(params[:id])
    @book_sidebar = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    # @user.id  = current_user.id
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

Bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers2/app/helpers/books_helper.rb
module BooksHelper
end

Bookers2/app/helpers/home_helper.rb
module HomeHelper
end

Bookers2/app/helpers/users_helper.rb
module UsersHelper
end

Bookers2/app/views/books/_sidebar.html.erb
<!-----------------------User info-------------------------------------------->
<div class="col-md-3">
  <h2 class="py-2">User info</h2>
  <table class="table">
    <%=attachment_image_tag user, :profile_image, :fill, 70, 70, fallback: "no_image.jpg", class: 'mb-3' %>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    </table>
       <%= link_to edit_user_path(user), class: "btn btn-outline-secondary w-100 p-0" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
<!-----------------------New Book-------------------------------------------->
  <h2 class="py-2 mt-2">New book</h2>
    <div class="text-danger mb-3">
          <% if book.errors.any? %>
            <h2><%= pluralize(book.errors.count, "error") %> prohibited this obj from being saved:</h2>
            <ul>
              <% book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>

    <%= form_with model: book, url: books_path, local:true do |f| %>
      <h6 class="py-1 mt-2 mb-0">Title</h6>
       <%= f.text_field :title %>
      <h6 class="py-1 mt-3 mb-0">Opinion</h6>
        <%= f.text_area :body %>
        <%= f.submit "Create Book", class: "btn btn-success mt-2" %>
    <% end %>
</div>
<!------------------------------memo-------------------------------------->

<!--@user → userへ変更-->
<!--@book → bookへ変更-->

<!--users 呼び出しview側-->
<%#= render 'users/sidebar', user: @user %>
<%#= render 'users/sidebar', book: @book %>

<!--books 呼び出しview側-->
<%#= render 'books/sidebar', user: @user %>
<%#= render 'books/sidebar', book: @book %>

Bookers2/app/views/books/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
  <h2 class="w-100 mt-3">Editing Book</h2>
    <div class="text-danger mt-3">
      <% if @book.errors.any? %>
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="w-100">
      <%= form_with model: @book, url: book_path(@book), local:true do |f| %>
      <h6>Title</h6>
        <%= f.text_field :title, class: "w-100" %>
      <h6 class="mt-3">Oipnion</h6>
        <%= f.text_area :body, class: "w-100" %>
        <%= f.submit "Update Book", class: "text-white btn btn-success mb-2 d-block" %>
      <% end %>
    </div>
    <div class="w-100">
      <%= link_to "Show", book_path(@book) %>
      <span> | </span>
      <%= link_to "Back", books_path %>
    </div>
</div>

Bookers2/app/views/books/index.html.erb
<%= render 'books/sidebar', user: @user, book: @book %>

<div class="col-md-8 offset-md-1 py-2">
  <h2>Books</h2>
  <table class="table">
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
    <% @books.each do |books| %>
    <tr>
      <td>
        <%=link_to user_path(books.user.id) do %>
          <%=attachment_image_tag books.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg" %>
        <% end %>
      </td>
      <td><%= link_to books.title, book_path(books.id) %></td>
      <td><%= books.body %></td>
    </tr>
    <% end %>
  </table>
</div>

Bookers2/app/views/books/show.html.erb
<%= render 'books/sidebar', user: @user_sidebar, book: @book_sidebar %>

<div class="col-md-8 offset-md-1 py-2">
  <h2>Book detail</h2>
  <table class="table">
    <tr>
      <td>
        <%=attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", class: 'mb-0' %>
        <p><%= link_to @book.user.name, user_path(@book.user) %></p>
      </td>
      <td><%= link_to @book.title, book_path(@book) %></td>
      <td><%= @book.body %></td>
      <td>
        <% if @book.user == current_user %>
          <%= link_to "Edit", edit_book_path(@book), class: "text-white btn btn-success btn-sm" %>
        <% end %>
      </td>
      <td>
        <% if @book.user == current_user %>
          <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class: "text-white btn btn-danger btn-sm" %>
        <% end %>
      </td>
    </tr>
  </table>
</div>

Bookers2/app/views/home/about.html.erb
<div class="mt-3 mx-0 text-center">
  <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
</div>

Bookers2/app/views/home/top.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
  <h1 class="jquery">Hello jQuery!</h1>
  <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
    <p class="mb-3">in <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
    <p class="mb-3">you can share and exchange your opinions , inpressions , and emotions</p>
    <p class="mb-3">about various books!</p>

  <div class="row">
      <%= link_to "Log in", new_user_session_path, class: "text-white btn btn-info btn-sm px-5 mb-2 mx-auto w-75" %>
  </div>
  <div class="row">
      <%= link_to "sign up", new_user_registration_path, class: "text-white btn btn-success btn-sm px-5 mb-2 mx-auto w-75" %>
  </div>
</div>

Bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title class="p-0">Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--meta name="viewport"追加-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-1" href="/">Bookers</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                  <li class="nav-item">
                   <%= link_to user_path(current_user.id), class: 'nav-link text-white' do %>
                     <i class="fas fa-home text-white mx-1"></i>Home
                   <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to users_path, class: 'nav-link text-white' do %>
                      <i class="fas fa-users text-white mx-1"></i>Users
                    <% end %>
                  </li>
                  <li class="nav-item">
                   <%= link_to books_path, class: 'nav-link text-white' do %>
                     <i class="fas fa-book-open text-white mx-1"></i>Books
                   <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white' do %>
                      <i class="fas fa-sign-out-alt text-white mx-1"></i>logout
                    <% end %>
                  </li>
                <% else %>
                  <li class="nav-item">
                   <%= link_to  root_path, class: 'nav-link text-white' do %>
                     <i class="fas fa-home text-white mx-1"></i>Home
                   <% end %>
                  </li>
                  <li class="nav-item">
                   <%= link_to home_about_path, class: 'nav-link text-white' do %>
                     <i class="fas fa-link text-white mx-1"></i>About
                   <% end %>
                  </li>
                  <li class="nav-item">
                   <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
                     <i class="fas fa-user-plus text-white mx-1"></i>Sign up
                   <% end %>
                  </li>
                   <li class="nav-item">
                   <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
                     <i class="fas fa-sign-in-alt text-white mx-1"></i>login
                   <% end %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>

      <main>
        <p class="text-success"><%= notice %></p>
        <div class="container">
          <div class="row">
              <%= yield %>
          </div>
        </div>
      </main>
      <footer class="mx-auto my-5">
        <p>CopyRight Infratop.inc</p>
      </footer>
        <div id="container">
          <div id="theTarget">
            <div class="image1"></div>
            <div class="image2"></div>
            <div class="image3"></div>
            <div class="image4"></div>
            <div class="image5"></div>
          </div>
        </div>
  </body>
</html>

Bookers2/app/views/users/_sidebar.html.erb
<!-----------------------User info-------------------------------------------->
<div class="col-md-3">
  <h2 class="py-2">User info</h2>
  <table class="table">
    <%=attachment_image_tag user, :profile_image, :fill, 70, 70, fallback: "no_image.jpg", class: 'mb-3' %>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </table>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary w-100 p-0" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
<!-----------------------New Book-------------------------------------------->
  <h2 class="py-2 mt-2">New book</h2>
    <div class="text-danger mb-3">
          <% if book.errors.any? %>
            <h2><%= pluralize(book.errors.count, "error") %> prohibited this obj from being saved:</h2>
            <ul>
              <% book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>

    <%= form_with model: book, url: books_path, local:true do |f| %>
      <h6 class="py-1 mt-2 mb-0">Title</h6>
       <%= f.text_field :title %>
      <h6 class="py-1 mt-3 mb-0">Opinion</h6>
        <%= f.text_area :body %>
        <%= f.submit "Create Book", class: "btn btn-success mt-2" %>
    <% end %>
</div>

<!------------------------------memo-------------------------------------->
<!--@user → userへ変更-->
<!--@book → bookへ変更-->

<!--users 呼び出しview側-->
<%#= render 'users/sidebar', user: @user %>
<%#= render 'users/sidebar', book: @book %>

<!--books 呼び出しview側-->
<%#= render 'books/sidebar', user: @user %>
<%#= render 'post_books/sidebar', book: @book %>

Bookers2/app/views/users/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
  <h2 class="w-100 mt-3">User info</h2>
  <div class="text-danger mb-3">
    <% if @user.errors.any? %>
    <h2><%= @user.errors.count %>error prohibited this obj from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="w-100">
    <%= form_with model: @user, local:true do |f| %>
    <h6>Name</h6>
      <%= f.text_field :name, class: "w-100" %>
    <label class="mt-3">Image</label>
      <%= f.attachment_field :profile_image, placefolder: "ファイルを選択", class: "d-block" %>
    <h6 class="mt-3">Introduction</h6>
      <%= f.text_area :introduction, class: "w-100"%>
      <%= f.submit "Update User", class: "text-white btn btn-secondary mb-2 d-block" %>
    <% end %>
  </div>
</div>

Bookers2/app/views/users/index.html.erb
<%= render 'users/sidebar', user: @user_sidebar, book: @book_sidebar %>
<div class="col-md-8 offset-md-1 py-2">
  <h2 class="py-2 mb-0">Users</h2>
  <table class="table">
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
    <% @users.each do |users| %>
    <tr>
      <td><%=attachment_image_tag users, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg" %></td>
      <td><%= users.name %></td>
      <td><%= link_to "Show", user_path(users.id) %></td>
    </tr>
    <% end %>
  </table>
</div>

Bookers2/app/views/users/show.html.erb
<%= render 'books/sidebar', user: @user_sidebar, book: @book_sidebar %>

<div class="col-md-8 offset-md-1 py-2">
  <h2>Books</h2>
  <table class="table">
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
    <% @books.each do |books| %>
    <tr>
      <td>
        <%=link_to user_path(books.user.id) do %>
          <%=attachment_image_tag books.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %>
        <% end %>
      </td>
      <td><%= link_to books.title, book_path(books.id) %></td>
      <td><%= books.body %></td>
    </tr>
    <% end %>
  </table>
</div>